export const videoList = [
  "https://youtu.be/XV_NXxiwe_w",
  "https://youtu.be/L6OVdO0TsIM",
  "https://youtu.be/tPv4xUYb3ek",
  "https://youtu.be/i1IY-jsHIrw",
  "https://youtu.be/i1IY-jsHIrw",
  "https://youtu.be/oSMsjvmrEYA",
];

export const clientLogo = [
  "https://cdn.qiblat.my.id/logo-bic.png",
  "https://cdn.qiblat.my.id/logo-hyundai.png",
  "https://cdn.qiblat.my.id/logo-altaura.png",
  "https://cdn.qiblat.my.id/logo-holigrels.png",
  "https://cdn.qiblat.my.id/logo-dasgo.PNG",
  "https://cdn.qiblat.my.id/logo-komerce.png",
  "https://cdn.qiblat.my.id/logo-bpjstk.png",
  "https://cdn.qiblat.my.id/logo-drg.png",
  "https://cdn.qiblat.my.id/logo-impa.png",
  "https://cdn.qiblat.my.id/logo-pgi.png",
  "https://cdn.qiblat.my.id/logo-pippit.webp",
  "https://cdn.qiblat.my.id/logo-dental.webp",
  "https://cdn.qiblat.my.id/logo-pp.png",
  "https://cdn.qiblat.my.id/logo-supa.png",
  "https://cdn.qiblat.my.id/logo-telkomsel.png",
  "https://cdn.qiblat.my.id/logo-idp1.png",
  "https://cdn.qiblat.my.id/logo-ckb.png",
  "https://cdn.qiblat.my.id/logo-belajarlagi.png",
  "https://cdn.qiblat.my.id/logo-capcut.png",
  "https://cdn.qiblat.my.id/logo-omago.png",
  "https://cdn.qiblat.my.id/logo-kelaside.png",
  "https://cdn.qiblat.my.id/logo-fraghead.png",
  "https://cdn.qiblat.my.id/logo-mfc.png",
];
